--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/kayy0812/BlackSmith
build-by-default: true
branches:
- master
projects:
  BlackSmith:
    path: ""
    lint:
      phpstan: false
...
